{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using GPUs: 0,\n"
     ]
    }
   ],
   "source": [
    "BATCH_SIZE = 4\n",
    "N_GPUS = 1\n",
    "ACCUMULATE_BATCHES = 1\n",
    "ckpt_path = \"/root/individual/hello2mao/models/sd-v1.4/sd-v1-4-full-ema.ckpt\"\n",
    "\n",
    "gpu_list = \",\".join((str(x) for x in range(N_GPUS))) + \",\"\n",
    "print(f\"Using GPUs: {gpu_list}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Global seed set to 23\n",
      "Running on GPUs 0\n",
      "LatentDiffusion: Running in eps-prediction mode\n",
      "DiffusionWrapper has 859.52 M params.\n",
      "Keeping EMAs of 688.\n",
      "making attention of type 'vanilla' with 512 in_channels\n",
      "Working with z of shape (1, 4, 32, 32) = 4096 dimensions.\n",
      "making attention of type 'vanilla' with 512 in_channels\n",
      "Downloading: \"https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth\" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 1354, in do_open\n",
      "    h.request(req.get_method(), req.selector, req.data, headers,\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 1256, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 1302, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 1251, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 1011, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 951, in send\n",
      "    self.connect()\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 1418, in connect\n",
      "    super().connect()\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/http/client.py\", line 922, in connect\n",
      "    self.sock = self._create_connection(\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/socket.py\", line 808, in create_connection\n",
      "    raise err\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/socket.py\", line 796, in create_connection\n",
      "    sock.connect(sa)\n",
      "ConnectionRefusedError: [Errno 111] Connection refused\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"main.py\", line 672, in <module>\n",
      "    model = instantiate_from_config(config.model)\n",
      "  File \"/root/individual/hello2mao/aigc-test/pokemon_stable_diffusion/ldm/util.py\", line 79, in instantiate_from_config\n",
      "    return get_obj_from_str(config[\"target\"])(**config.get(\"params\", dict()))\n",
      "  File \"/root/individual/hello2mao/aigc-test/pokemon_stable_diffusion/ldm/models/diffusion/ddpm.py\", line 526, in __init__\n",
      "    self.instantiate_cond_stage(cond_stage_config)\n",
      "  File \"/root/individual/hello2mao/aigc-test/pokemon_stable_diffusion/ldm/models/diffusion/ddpm.py\", line 584, in instantiate_cond_stage\n",
      "    model = instantiate_from_config(config)\n",
      "  File \"/root/individual/hello2mao/aigc-test/pokemon_stable_diffusion/ldm/util.py\", line 79, in instantiate_from_config\n",
      "    return get_obj_from_str(config[\"target\"])(**config.get(\"params\", dict()))\n",
      "  File \"/root/individual/hello2mao/aigc-test/pokemon_stable_diffusion/ldm/util.py\", line 87, in get_obj_from_str\n",
      "    return getattr(importlib.import_module(module, package=None), cls)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/root/individual/hello2mao/aigc-test/pokemon_stable_diffusion/ldm/modules/encoders/modules.py\", line 5, in <module>\n",
      "    import kornia\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/__init__.py\", line 10, in <module>\n",
      "    from . import (\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/augmentation/__init__.py\", line 43, in <module>\n",
      "    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/augmentation/container/__init__.py\", line 1, in <module>\n",
      "    from .augment import AugmentationSequential\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/augmentation/container/augment.py\", line 17, in <module>\n",
      "    from .patch import PatchSequential\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/augmentation/container/patch.py\", line 9, in <module>\n",
      "    from kornia.contrib.extract_patches import extract_tensor_patches\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/contrib/__init__.py\", line 4, in <module>\n",
      "    from .image_stitching import ImageStitcher\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/contrib/image_stitching.py\", line 7, in <module>\n",
      "    from kornia.feature import LocalFeatureMatcher, LoFTR\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/feature/__init__.py\", line 4, in <module>\n",
      "    from .integrated import (\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/feature/integrated.py\", line 52, in <module>\n",
      "    class LAFDescriptor(nn.Module):\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/feature/integrated.py\", line 65, in LAFDescriptor\n",
      "    patch_descriptor_module: nn.Module = HardNet(True),\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/kornia/feature/hardnet.py\", line 66, in __init__\n",
      "    pretrained_dict = torch.hub.load_state_dict_from_url(\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/torch/hub.py\", line 727, in load_state_dict_from_url\n",
      "    download_url_to_file(url, cached_file, hash_prefix, progress=progress)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/site-packages/torch/hub.py\", line 593, in download_url_to_file\n",
      "    u = urlopen(req)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 222, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 531, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 640, in http_response\n",
      "    response = self.parent.error(\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 563, in error\n",
      "    result = self._call_chain(*args)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 755, in http_error_302\n",
      "    return self.parent.open(new, timeout=req.timeout)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 525, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 542, in _open\n",
      "    result = self._call_chain(self.handle_open, protocol, protocol +\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 1397, in https_open\n",
      "    return self.do_open(http.client.HTTPSConnection, req,\n",
      "  File \"/root/miniconda3/envs/aigc/lib/python3.8/urllib/request.py\", line 1357, in do_open\n",
      "    raise URLError(err)\n",
      "urllib.error.URLError: <urlopen error [Errno 111] Connection refused>\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"main.py\", line 939, in <module>\n",
      "    if trainer.global_rank == 0:\n",
      "NameError: name 'trainer' is not defined\n"
     ]
    }
   ],
   "source": [
    "# Run training\n",
    "!(python main.py \\\n",
    "    -t \\\n",
    "    --base configs/stable-diffusion/pokemon.yaml \\\n",
    "    --gpus 0 \\\n",
    "    --scale_lr False \\\n",
    "    --num_nodes 1 \\\n",
    "    --check_val_every_n_epoch 10 \\\n",
    "    --finetune_from \"$ckpt_path\" \\\n",
    "    data.params.batch_size=\"$BATCH_SIZE\" \\\n",
    "    lightning.trainer.accumulate_grad_batches=\"$ACCUMULATE_BATCHES\" \\\n",
    "    data.params.validation.params.n_gpus=\"$NUM_GPUS\" \\\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.8.16 ('aigc')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.16"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "9c2885a011615edd7c4edfe7b45d4d0e7e6655fb2f294de0a5ad35d94d68e8f2"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
